-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWvC1M2BMCgm8OuyP
es7QkcrTWBRuaRa54rys0G9quR+gCgYIKoZIzj0DAQehRANCAASNzmwU1dw/5j/6
RuPfFGXo4FP4QJ29oQFweEw8tidGsanOnooTNUBJBpqqIKGisk0NAMsCa+mpzTu5
RolP5rif
-----END PRIVATE KEY-----