// Based on the CSV data provided
const weddingTasksData = {
  null: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: null,
    isCompleted: false,
    category: null,
    tasks: [
      {
        name: "Decide your top three priorities",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 1,
          6: 1,
          9: 1,
          12: 1,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 6,
          12: 7,
        },
        priority: 1,
      },
      {
        name: "Spend time learning more on the budget page",
        navigation: "/budget",
        isCompleted: false,
        category: "Budget",
        deadlines: {
          3: 1,
          6: 1,
          9: 2,
          12: 2,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 6,
          12: 7,
        },
        priority: 2,
      },
      {
        name: "Begin adding helpers to a list",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 1,
          6: 3,
          9: 5,
          12: 6,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 5,
          12: 7,
        },
        priority: 6,
      },
      {
        name: "Choose wedding party",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 2,
          6: 4,
          9: 6,
          12: 7,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 5,
          12: 7,
        },
        priority: 7,
      },
      {
        name: "Keep adding to your regestries",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 4,
          6: 9,
          9: 13,
          12: 18,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 6,
        },
        priority: 23,
      },
      {
        name: "Reserve lodging if necessary (before ordering invitations)",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 4,
          6: 9,
          9: 14,
          12: 19,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 25,
      },
      {
        name: 'Schedule meeting with key helpers (see advice drawer in "PLAN" icon)',
        navigation: null,
        isCompleted: false,
        category: "?",
        deadlines: {
          3: 4,
          6: 9,
          9: 14,
          12: 19,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 26,
      },
      {
        name: "Check registries",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 7,
          6: 15,
          9: 24,
          12: 32,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 55,
      },
      {
        name: "Wedding party/family gifts",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 8,
          6: 17,
          9: 27,
          12: 36,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 70,
      },
      {
        name: "Thank you's for helpers & others",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 8,
          6: 18,
          9: 28,
          12: 36,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 71,
      },
      {
        name: 'Purchase & begin "Thank You\'s"',
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 9,
          6: 19,
          9: 30,
          12: 39,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 2,
          12: 2,
        },
        priority: 75,
      },
      {
        name: "Start breaking in your shoes",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 9,
          6: 20,
          9: 31,
          12: 41,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 79,
      },
      {
        name: "Delgate speeches & other jobs",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 10,
          6: 21,
          9: 33,
          12: 44,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 87,
      },
      {
        name: "Arrange for any final payments",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 12,
          6: 25,
          9: 38,
          12: 51,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 96,
      },
      {
        name: "Gather license, vows, rings",
        navigation: null,
        isCompleted: false,
        category: null,
        deadlines: {
          3: 13,
          6: 26,
          9: 39,
          12: 52,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 98,
      },
    ],
  },
  "Venue Checklist": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Venue Checklist",
    isCompleted: false,
    category: "Wedding Location",
    tasks: [
      {
        name: "Search & compare locations",
        navigation: "/compareVenues",
        isCompleted: false,
        category: "Wedding Location",
        deadlines: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 6,
          12: 7,
        },
        priority: 4,
      },
      {
        name: "Choose & reserve location(s)",
        navigation: "/compareVenues",
        isCompleted: false,
        category: "Wedding Location",
        deadlines: {
          3: 2,
          6: 5,
          9: 7,
          12: 10,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 5,
          12: 6,
        },
        priority: 10,
      },
      {
        name: "Plan & arrange for venue essentials",
        navigation: "/planVenueEssentials",
        isCompleted: false,
        category: "Wedding Location",
        deadlines: {
          3: 4,
          6: 10,
          9: 15,
          12: 20,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 28,
      },
      {
        name: "Confirm general info with venue",
        navigation: "/venue",
        isCompleted: false,
        category: "Wedding Location",
        deadlines: {
          3: 10,
          6: 21,
          9: 33,
          12: 43,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 85,
      },
      {
        name: "Set-up venue",
        navigation: "/venue",
        isCompleted: false,
        category: "Wedding Location",
        deadlines: {
          3: 13,
          6: 26,
          9: 39,
          12: 52,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 100,
      },
    ],
  },
  Website: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Website",
    isCompleted: false,
    category: "Communication",
    tasks: [
      {
        name: "Create wedding website",
        navigation: "/communication",
        isCompleted: false,
        category: "Communication",
        deadlines: {
          3: 2,
          6: 4,
          9: 7,
          12: 9,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 5,
          12: 7,
        },
        priority: 9,
      },
      {
        name: "Set up wedding registry",
        navigation: "/communication",
        isCompleted: false,
        category: "Communication",
        deadlines: {
          3: 3,
          6: 7,
          9: 11,
          12: 15,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 5,
          12: 6,
        },
        priority: 15,
      },
    ],
  },
  "Save the Date": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Save the Date",
    isCompleted: false,
    category: "Communication",
    tasks: [
      {
        name: 'Create/Order "Save the Dates"',
        navigation: "/communication",
        isCompleted: false,
        category: "Communication",
        deadlines: {
          3: 2,
          6: 6,
          9: 8,
          12: 12,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 5,
          12: 6,
        },
        priority: 13,
      },
      {
        name: 'Address/Send "Save the Dates"',
        navigation: "/communication",
        isCompleted: false,
        category: "Communication",
        deadlines: {
          3: 4,
          6: 9,
          9: 14,
          12: 19,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 27,
      },
    ],
  },
  Invitations: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Invitations",
    isCompleted: false,
    category: "Communication",
    tasks: [
      {
        name: "Create/Order invitations",
        navigation: "/communication",
        isCompleted: false,
        category: "Communication",
        deadlines: {
          3: 3,
          6: 8,
          9: 13,
          12: 18,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 4,
          12: 6,
        },
        priority: 22,
      },
      {
        name: "Address/Send invitations",
        navigation: "/communication",
        isCompleted: false,
        category: "Communication",
        deadlines: {
          3: 4,
          6: 11,
          9: 17,
          12: 22,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 35,
      },
    ],
  },
  Programs: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Programs",
    isCompleted: false,
    category: "Communication",
    tasks: [
      {
        name: "Create/Order programs",
        navigation: "/communication",
        isCompleted: false,
        category: "Communication",
        deadlines: {
          3: 10,
          6: 21,
          9: 33,
          12: 43,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 83,
      },
    ],
  },
  Photographer: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Photographer",
    isCompleted: false,
    category: "Photo & Video",
    tasks: [
      {
        name: "Compare photographers",
        navigation: "/comparePhoto",
        isCompleted: false,
        category: "Photo & Video",
        deadlines: {
          3: 3,
          6: 8,
          9: 11,
          12: 16,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 5,
          12: 6,
        },
        priority: 17,
      },
      {
        name: "Choose photograper",
        navigation: "/comparePhoto",
        isCompleted: false,
        category: "Photo & Video",
        deadlines: {
          3: 5,
          6: 11,
          9: 17,
          12: 22,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 40,
      },
      {
        name: "Create a photo shot list",
        navigation: "/photoVideo",
        isCompleted: false,
        category: "Photo & Video",
        deadlines: {
          3: 8,
          6: 17,
          9: 26,
          12: 35,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 66,
      },
      {
        name: "Take engagement photos",
        navigation: "/photoVideo",
        isCompleted: false,
        category: "Photo & Video",
        deadlines: {
          3: 2,
          6: 5,
          9: 8,
          12: 11,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 5,
          12: 6,
        },
        priority: 11,
      },
      {
        name: "Share photo list/info with photo & video",
        navigation: "/photoVideo",
        isCompleted: false,
        category: "Photo & Video",
        deadlines: {
          3: 9,
          6: 20,
          9: 31,
          12: 41,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 80,
      },
    ],
  },
  Videographer: {
    checkBox: true,
    label: "Same as photographer",
    checkBoxValue: false,
    name: "Videographer",
    isCompleted: false,
    category: "Photo & Video",
    tasks: [
      {
        name: "Compare videographers",
        navigation: "/compareVideo",
        isCompleted: false,
        category: "Photo & Video",
        deadlines: {
          3: 3,
          6: 8,
          9: 11,
          12: 16,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 5,
          12: 6,
        },
        priority: 18,
      },
      {
        name: "Choose videographer",
        navigation: "/compareVideo",
        isCompleted: false,
        category: "Photo & Video",
        deadlines: {
          3: 5,
          6: 11,
          9: 17,
          12: 22,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 41,
      },
    ],
  },
  Legal: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Legal",
    isCompleted: false,
    category: "Odds & Ends",
    tasks: [
      {
        name: "Check on marriage license",
        navigation: "/legalScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 2,
          6: 5,
          9: 8,
          12: 12,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 5,
          12: 6,
        },
        priority: 12,
      },
      {
        name: "Check on Event Insurance",
        navigation: "/legalScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 6,
          6: 13,
          9: 20,
          12: 27,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 48,
      },
      {
        name: 'Check "Name change" information',
        navigation: null,
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 9,
          6: 19,
          9: 30,
          12: 39,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 2,
          12: 2,
        },
        priority: 76,
      },
    ],
  },
  Official: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Official",
    isCompleted: false,
    category: "Odds & Ends",
    tasks: [
      {
        name: "Retain officiant",
        navigation: "/officialScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 5,
          6: 11,
          9: 17,
          12: 22,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 37,
      },
      {
        name: "Meet with offficant",
        navigation: "/officialScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 11,
          6: 24,
          9: 36,
          12: 49,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 1,
        },
        priority: 94,
      },
      {
        name: "Work on vows",
        navigation: "/officialScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 10,
          6: 22,
          9: 34,
          12: 44,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 88,
      },
      {
        name: "Schedule premarital counseling",
        navigation: null,
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 1,
          6: 2,
          9: 3,
          12: 3,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 6,
          12: 7,
        },
        priority: 3,
      },
    ],
  },
  Miscellaneous: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Miscellaneous",
    isCompleted: false,
    category: "Odds & Ends",
    tasks: [
      {
        name: "Decide on party favors",
        navigation: "/miscellaneousScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 5,
          6: 11,
          9: 18,
          12: 24,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 44,
      },
      {
        name: "Purchase Rings",
        navigation: "/miscellaneousScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 5,
          6: 11,
          9: 17,
          12: 22,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 36,
      },
      {
        name: "Plan honeymoon",
        navigation: "/miscellaneousScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: 3,
          6: 8,
          9: 12,
          12: 17,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 4,
          12: 6,
        },
        priority: 21,
      },
    ],
  },
  "Post Wedding": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Post Wedding",
    isCompleted: false,
    category: "Odds & Ends",
    tasks: [
      {
        name: "Decide what to do with my dress",
        navigation: "/postWeddingScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: null,
          6: null,
          9: null,
          12: null,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: null,
      },
      {
        name: "Reminders",
        navigation: "/postWeddingScreen",
        isCompleted: false,
        category: "Odds & Ends",
        deadlines: {
          3: null,
          6: null,
          9: null,
          12: null,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: null,
      },
    ],
  },
  "Bride Outfit": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Bride Outfit",
    isCompleted: false,
    category: "Attire",
    tasks: [
      {
        name: "Search & compare bridal dress",
        navigation: "/compareBridalDresses",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 6,
          12: 7,
        },
        priority: 5,
      },
      {
        name: "Choose bridal dress",
        navigation: "/compareBridalDresses",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 3,
          6: 7,
          9: 10,
          12: 15,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 5,
          12: 6,
        },
        priority: 14,
      },
      {
        name: "Schedule dress alterations",
        navigation: "/brideAlteration",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 3,
          6: 8,
          9: 12,
          12: 17,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 4,
          12: 6,
        },
        priority: 19,
      },
      {
        name: "Decide/Order other clothing items for bride",
        navigation: "/brideAlteration",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 7,
          6: 16,
          9: 25,
          12: 33,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 61,
      },
      {
        name: "Final check of bridal outfit",
        // navigation: "/compareBridalDresses",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 10,
          6: 22,
          9: 34,
          12: 44,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 89,
      },
    ],
  },
  Groom: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Groom",
    isCompleted: false,
    category: "Attire",
    tasks: [
      {
        name: "Search for groom's outfit",
        navigation: "/compareGroomDresses",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 3,
          6: 8,
          9: 12,
          12: 17,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 4,
          12: 6,
        },
        priority: 20,
      },
      {
        name: "Choose groom's outfit",
        navigation: "/compareGroomDresses",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 4,
          6: 10,
          9: 16,
          12: 21,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 30,
      },
      {
        name: "Schedule groom's alterations",
        navigation: "/groomAlteration",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 4,
          6: 10,
          9: 16,
          12: 21,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 34,
      },
      {
        name: "Purchase Groom's Misc. Items",
        navigation: "/groomAlteration",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 7,
          6: 15,
          9: 24,
          12: 32,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 56,
      },
    ],
  },
  Bridesmaids: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Bridesmaids",
    isCompleted: false,
    category: "Attire",
    tasks: [
      {
        name: "Choose bridesmaid dresses",
        navigation: "/bridesmaids",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 4,
          6: 10,
          9: 16,
          12: 21,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 31,
      },
      {
        name: "Bridesmaid dresses ordered",
        navigation: "/bridesmaids",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 7,
          6: 15,
          9: 24,
          12: 32,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 57,
      },
      {
        name: "Decide/Order accessories for bridesmaids",
        navigation: "/bridesmaids",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 7,
          6: 15,
          9: 25,
          12: 33,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 59,
      },
    ],
  },
  Groomsmen: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Groomsmen",
    isCompleted: false,
    category: "Attire",
    tasks: [
      {
        name: "Choose groomsmen attire",
        navigation: "/groomsmen",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 4,
          6: 10,
          9: 16,
          12: 21,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 32,
      },
      {
        name: "Groomsmen's outfits ordered",
        navigation: "/groomsmen",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 7,
          6: 15,
          9: 24,
          12: 32,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 58,
      },
      {
        name: "Decide/Order accessories for groomsmen",
        navigation: "/groomsmen",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 7,
          6: 15,
          9: 25,
          12: 33,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 60,
      },
    ],
  },
  "Other Outfits": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Other",
    isCompleted: false,
    category: "Attire",
    tasks: [
      {
        name: 'Choose "others" outfits',
        navigation: "/childrenOthers",
        isCompleted: false,
        category: "Attire",
        deadlines: {
          3: 4,
          6: 10,
          9: 16,
          12: 21,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 33,
      },
    ],
  },
  "Floral Checklist": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Floral Checklist",
    isCompleted: false,
    notes: [
      {
        placeholder:
          "See your floral spreadsheet and use this space to add notes for reference (optional).",
      },
    ],
    category: "Floral & Decor",
    tasks: [
      {
        name: "Design florals & decor",
        navigation: "/designFloral",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 5,
          6: 11,
          9: 17,
          12: 23,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 42,
      },
      {
        name: "Make Decor Supply List",
        navigation: "/orderSupplies",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 5,
          6: 12,
          9: 19,
          12: 25,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 3,
          12: 5,
        },
        priority: 47,
      },
      {
        name: "Plan times to work on decor",
        navigation: "/floral",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 7,
          6: 15,
          9: 23,
          12: 31,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 54,
      },
      {
        name: "Order non perishables",
        navigation: "/constructFloral",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 6,
          6: 14,
          9: 22,
          12: 30,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 51,
      },
      {
        name: "Order perishable decor",
        navigation: "/constructFloral",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 10,
          6: 22,
          9: 34,
          12: 45,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 1,
        },
        priority: 90,
      },
      {
        name: "Florals & decor set-up",
        navigation: "/floral",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 13,
          6: 26,
          9: 39,
          12: 52,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 101,
      },
      {
        name: "Confirm with florist",
        navigation: "/floral",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 10,
          6: 21,
          9: 33,
          12: 43,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 86,
      },
    ],
  },
  "Linens Checklist": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Linens Checklist",
    isCompleted: false,
    category: "Floral & Decor",
    tasks: [
      {
        name: "Decide on linen needs",
        navigation: "/linens",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 5,
          6: 11,
          9: 17,
          12: 23,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 43,
      },
      {
        name: "Order linens",
        navigation: "/orderSupplies",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 6,
          6: 14,
          9: 22,
          12: 30,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 52,
      },
      {
        name: "Linen Care / Assign",
        navigation: "/linens",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 9,
          6: 19,
          9: 31,
          12: 40,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 77,
      },
    ],
  },
  "Lighting Checklist": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Lighting Checklist",
    isCompleted: false,
    category: "Floral & Decor",
    tasks: [
      {
        name: "Decide lighting needs",
        navigation: "/lighting",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 5,
          6: 11,
          9: 18,
          12: 24,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 45,
      },
      {
        name: "Order lighting",
        navigation: "/orderSupplies",
        isCompleted: false,
        category: "Floral & Decor",
        deadlines: {
          3: 6,
          6: 14,
          9: 22,
          12: 30,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 53,
      },
    ],
  },
  "Guest List": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Guest List",
    isCompleted: false,
    category: "Guests",
    tasks: [
      {
        name: "Create a guest list",
        navigation: "/guestList",
        isCompleted: false,
        category: "Guests",
        deadlines: {
          3: 2,
          6: 4,
          9: 6,
          12: 8,
        },
        extensions: {
          3: 2,
          6: 4,
          9: 5,
          12: 7,
        },
        priority: 8,
      },
      {
        name: "Add guests to list",
        navigation: "/guestList",
        isCompleted: false,
        category: "Guests",
        deadlines: {
          3: 3,
          6: 7,
          9: 11,
          12: 16,
        },
        extensions: {
          3: 2,
          6: 3,
          9: 5,
          12: 6,
        },
        priority: 16,
      },
      {
        name: "Finalize guest list",
        navigation: "/guestList",
        isCompleted: false,
        category: "Guests",
        deadlines: {
          3: 4,
          6: 9,
          9: 13,
          12: 18,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 6,
        },
        priority: 24,
      },
      {
        name: "Plan RSVP Confirmation",
        navigation: "/guestSeating",
        isCompleted: false,
        category: "Guests",
        deadlines: {
          3: 9,
          6: 20,
          9: 32,
          12: 42,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 81,
      },
    ],
  },
  "Seating Charts": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Seating Charts",
    isCompleted: false,
    category: "Guests",
    tasks: [
      {
        name: "Make Seating chart",
        navigation: "/guestSeatingChart",
        isCompleted: false,
        category: "Guests",
        deadlines: {
          3: 10,
          6: 21,
          9: 31,
          12: 43,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 84,
      },
      {
        name: "Design seating chart display",
        navigation: "/guestSeatingChart",
        isCompleted: false,
        category: "Guests",
        deadlines: {
          3: 5,
          6: 11,
          9: 18,
          12: 24,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 46,
      },
    ],
  },
  "Parties/Showers": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Parties/Showers",
    text: "Lorem ipsum dolor sit amet",
    isCompleted: false,
    category: "Guests",
    tasks: [],
  },
  "DIY Meals Checklist": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "DIY Meals Checklist",
    notes: [
      {
        placeholder: "Add menu notes (optional)",
      },
    ],
    isCompleted: false,
    category: "Food",
    tasks: [
      {
        name: "Decide/create menu",
        navigation: "/menuList",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 6,
          6: 13,
          9: 21,
          12: 28,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 49,
      },
      {
        name: "Organize/Assign DIY Food",
        navigation: "/menuList",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 7,
          6: 16,
          9: 25,
          12: 34,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 62,
      },
      {
        name: "Purchase non-perishable food items",
        navigation: "/foodCatering",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 8,
          6: 18,
          9: 29,
          12: 37,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 72,
      },
      {
        name: "Purchase perishable food",
        navigation: "/foodCatering",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 13,
          6: 26,
          9: 39,
          12: 52,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 99,
      },
      {
        name: "Food cook & prep",
        navigation: "/foodCatering",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 13,
          6: 26,
          9: 39,
          12: 52,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 102,
      },
      {
        name: "Confirm with all people bringing food items",
        navigation: "/foodCatering",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 11,
          6: 23,
          9: 36,
          12: 48,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 1,
        },
        priority: 93,
      },
    ],
  },
  Caterer: {
    checkBox: true,
    label: "Not going with caterers",
    checkBoxValue: false,
    name: "Caterer",
    isCompleted: false,
    category: "Food",
    tasks: [
      {
        name: "Compare caterers",
        navigation: "/compareCaterers",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 7,
          6: 16,
          9: 25,
          12: 34,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 63,
      },
      {
        name: "Choose caterer",
        navigation: "/compareCaterers",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 8,
          6: 18,
          9: 29,
          12: null,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 73,
      },
      {
        name: "Confirm with caterer",
        navigation: "/foodCatering",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 11,
          6: 23,
          9: 36,
          12: 48,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 1,
        },
        priority: 92,
      },
    ],
  },
  "Desserts and Beverages": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    notes: [
      {
        placeholder: "Add dessert notes (optional)",
      },
      {
        placeholder: "Add beverages notes (optional)",
      },
    ],
    name: "Desserts and Beverages",
    isCompleted: false,
    category: "Food",
    tasks: [
      {
        name: "Decide dessert/beverages",
        navigation: "/dessertsList",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 6,
          6: 13,
          9: 21,
          12: 28,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 3,
          12: 4,
        },
        priority: 50,
      },
      {
        name: "Organize/Assign/order Desserts",
        navigation: "/dessertsList",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 7,
          6: 16,
          9: 25,
          12: 34,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 64,
      },
      {
        name: "Organize/Assign/Order Beverages",
        navigation: "/dessertsList",
        isCompleted: false,
        category: "Food",
        deadlines: {
          3: 8,
          6: 18,
          9: 29,
          12: null,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 74,
      },
    ],
  },
  "Wedding Week": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Wedding Week",
    isCompleted: false,
    category: "Wedding Week",
    tasks: [
      {
        name: "Create set-up & clean-up schedule",
        navigation: "/scheduleWedding",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 8,
          6: 17,
          9: 27,
          12: null,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 69,
      },
    ],
  },
  Rehearsal: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Rehearsal",
    isCompleted: false,
    category: "Wedding Week",
    tasks: [
      {
        name: "Rehearsal",
        navigation: "/weddingWeek",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 13,
          6: 26,
          9: 39,
          12: 52,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 103,
      },
      {
        name: "Plan/delegate rehearsal dinner",
        navigation: "/weddingWeek",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 10,
          6: 21,
          9: 32,
          12: 42,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 82,
      },
      {
        name: "Rehearsal Dinner",
        navigation: "/weddingWeek",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 13,
          6: 26,
          9: 39,
          12: 52,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 104,
      },
      {
        name: 'Find a "Day of Coordinator" (or friend)',
        navigation: "/rehearsalScreen",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 8,
          6: 17,
          9: 26,
          12: 35,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 65,
      },
      {
        name: "Go through details with coordinator",
        navigation: "/weddingWeek",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 12,
          6: 25,
          9: 38,
          12: 51,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 97,
      },
    ],
  },
  "Order of Events": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Order of Events",
    isCompleted: false,
    category: "Wedding Week",
    tasks: [
      {
        name: "Plan order of events",
        navigation: "/eventsOrder",
        isCompleted: null,
        category: "Wedding Week",
        deadlines: {
          3: 8,
          6: 17,
          9: 26,
          12: 35,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 67,
      },
    ],
  },
  "Wedding Day": {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Wedding Day",
    isCompleted: false,
    category: "Wedding Week",
    tasks: [
      {
        name: "Create wedding day timeline",
        navigation: "/timelineSchedule",
        isCompleted: null,
        category: "Wedding Week",
        deadlines: {
          3: 8,
          6: 17,
          9: 26,
          12: 35,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: null,
      },
      {
        name: "Create wedding day timeline",
        navigation: "/timelineSchedule",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 8,
          6: 17,
          9: 26,
          12: 35,
        },
        extensions: {
          3: 1,
          6: 2,
          9: 2,
          12: 3,
        },
        priority: 68,
      },
      {
        name: "Give schedule to all others",
        navigation: "/timelineSchedule",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 12,
          6: 25,
          9: 38,
          12: 51,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 95,
      },
      {
        name: "WEDDING DAY!",
        navigation: "/weddingWeek",
        isCompleted: false,
        category: "Wedding Week",
        deadlines: {
          3: 13,
          6: 26,
          9: 39,
          12: 52,
        },
        extensions: {
          3: 0,
          6: 0,
          9: 0,
          12: 0,
        },
        priority: 105,
      },
    ],
  },
  Music: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Music",
    isCompleted: false,
    category: "Music",
    tasks: [
      {
        name: "Decide music for wedding & reception",
        navigation: null,
        isCompleted: false,
        category: "Music",
        deadlines: {
          3: 9,
          6: 19,
          9: 31,
          12: 40,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 2,
        },
        priority: 78,
      },
      {
        name: "Create playlists",
        navigation: "/createPlaylist",
        isCompleted: false,
        category: "Music",
        deadlines: {
          3: 11,
          6: 23,
          9: 35,
          12: 46,
        },
        extensions: {
          3: 1,
          6: 1,
          9: 1,
          12: 1,
        },
        priority: 91,
      },
    ],
  },
  Other: {
    checkBox: false,
    label: null,
    checkBoxValue: false,
    name: "Other",
    isCompleted: false,
    category: "Music",
    tasks: [
      {
        name: "Hire DJ/MC",
        navigation: "/musicSound",
        isCompleted: false,
        category: "Music",
        deadlines: {
          3: 5,
          6: 11,
          9: 17,
          12: 22,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 38,
      },
      {
        name: "Hire musicians",
        navigation: "/musicSound",
        isCompleted: false,
        category: "Music",
        deadlines: {
          3: 5,
          6: 11,
          9: 17,
          12: 22,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 39,
      },
      {
        name: "Find Sound System",
        navigation: "/soundSystem",
        isCompleted: false,
        category: "Music",
        deadlines: {
          3: 4,
          6: 10,
          9: 15,
          12: 20,
        },
        extensions: {
          3: 1,
          6: 3,
          9: 4,
          12: 5,
        },
        priority: 29,
      },
    ],
  },
};
// Function to calculate interpolated deadline
function calculateDueDate(task, weddingTimelineMonths) {
  const deadlines = task.deadlines;

  // Handle exact matches
  if (deadlines[weddingTimelineMonths]) {
    return deadlines[weddingTimelineMonths];
  }

  // Find the appropriate bracket for interpolation
  let lowerBound, upperBound, lowerDeadline, upperDeadline;

  if (weddingTimelineMonths < 3) {
    // Less than 3 months - use 3 month deadline
    return deadlines[3];
  } else if (weddingTimelineMonths > 12) {
    // More than 12 months - use 12 month deadline
    return deadlines[12];
  } else if (weddingTimelineMonths < 6) {
    // Between 3 and 6 months
    lowerBound = 3;
    upperBound = 6;
    lowerDeadline = deadlines[3];
    upperDeadline = deadlines[6];
  } else if (weddingTimelineMonths < 9) {
    // Between 6 and 9 months
    lowerBound = 6;
    upperBound = 9;
    lowerDeadline = deadlines[6];
    upperDeadline = deadlines[9];
  } else {
    // Between 9 and 12 months
    lowerBound = 9;
    upperBound = 12;
    lowerDeadline = deadlines[9];
    upperDeadline = deadlines[12];
  }

  // Linear interpolation formula
  const interpolatedDeadline =
    lowerDeadline +
    ((weddingTimelineMonths - lowerBound) / (upperBound - lowerBound)) *
      (upperDeadline - lowerDeadline);

  // Round to nearest whole week
  return Math.round(interpolatedDeadline);
}

function calculateDeadline(task, weddingTimelineMonths) {
  const extensions = task.extensions;

  // Handle exact matches
  if (extensions[weddingTimelineMonths]) {
    return extensions[weddingTimelineMonths];
  }

  // Find the appropriate bracket for interpolation
  let lowerBound, upperBound, lowerDeadline, upperDeadline;

  if (weddingTimelineMonths < 3) {
    // Less than 3 months - use 3 month deadline
    return extensions[3];
  } else if (weddingTimelineMonths > 12) {
    // More than 12 months - use 12 month deadline
    return extensions[12];
  } else if (weddingTimelineMonths < 6) {
    // Between 3 and 6 months
    lowerBound = 3;
    upperBound = 6;
    lowerDeadline = extensions[3];
    upperDeadline = extensions[6];
  } else if (weddingTimelineMonths < 9) {
    // Between 6 and 9 months
    lowerBound = 6;
    upperBound = 9;
    lowerDeadline = extensions[6];
    upperDeadline = extensions[9];
  } else {
    // Between 9 and 12 months
    lowerBound = 9;
    upperBound = 12;
    lowerDeadline = extensions[9];
    upperDeadline = extensions[12];
  }

  // Linear interpolation formula
  const interpolatedDeadline =
    lowerDeadline +
    ((weddingTimelineMonths - lowerBound) / (upperBound - lowerBound)) *
      (upperDeadline - lowerDeadline);

  // Round to nearest whole week
  return Math.round(interpolatedDeadline);
}
module.exports = {
  weddingTasksData,
  calculateDeadline, // Export the calculateDeadline function
  calculateDueDate,
};
