module.exports = {
  TASK_CATEGORIES: {
    searchAndCompareVenues: "Search & compare locations",
    chooseAndReserveLocations: "Choose & reserve location(s)",
    planAndArrangeVenueEssentials: "Plan & arrange for venue essentials",
    createFoodMenu: "Decide/create menu",
    organizeDiyFood: "Organize/Assign DIY Food",
    compareCaterers: "Compare caterers",
    chooseCaterer: "Choose caterer",
    decideDessertsBeverages: "Decide dessert/beverages",
    organizeDesserts: "Organize/Assign/order Desserts",
    organizeBeverages: "Organize/Assign/Order Beverages",
    searchBridalDresses: "Search & compare bridal dress",
    chooseBridalDresses: "Choose bridal dress",
    searchGroomOutfit: "Search for groom's outfit",
    chooseGroomOutfit: "Choose groom's outfit",
    scheduleBridalAlterations: "Schedule dress alterations",
    scheduleGroomAlterations: "Schedule groom's alterations",
    brideOtherClothing: "Decide/Order other clothing items for bride",
    groomOtherClothing: "Purchase Groom's Misc. Items",
    comparePhotographers: "Compare photographers",
    compareVideographers: "Compare videographers",
    choosePhotographer: "Choose photograper",
    chooseVideographer: "Choose videographer",
    checkMarriageLicense: "Check on marriage license",
    planHoneymoon: "Plan honeymoon",
    purchaseRings: "Purchase Rings",
    retainOfficiant: "Retain officiant",
    partyFavors: "Decide/Order party favors",
    eventInsurance: "Check on Event Insurance",
    vows: "Work on vows",
    meetOfficiant: "Meet with offficiant",
    dressDecision: "Decide what to do with my dress",
    reminders: "Reminders",
    chooseBridesmaidDresses: "Choose bridesmaid dresses",
    bridesmaidDressesOrdered: "Bridesmaid dresses ordered",
    bridesmaidAccesories: "Decide/Order accessories for bridesmaids",
    chooseGroomsmanAttire: "Choose groomsmen attire",
    groomsmenOutfitsOrdered: "Groomsmen's outfits ordered",
    groomsmenAccesories: "Decide/Order accessories for groomsmen",
    chooseOtherAttires: 'Choose "others" outfits',
    designFloralDecor: "Design florals & decor",
    makeDecorSupply: "Make Decor Supply List",
    createPlaylists: "Create playlists",
    findSoundSystem: "Find Sound System",
    spendTimeOnBudget: "Spend time learning more on the budget page",
  },
};
